name: pag_ems_tp
description: "Energy@Grid EMS Tenant Portal"
publish_to: 'none'
version: 0.3.1

environment:
  sdk: '>=3.6.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  provider: ^6.1.2
  go_router: ^14.6.2  
  package_info_plus: ^8.1.2
  material_symbols_icons: ^4.2801.0
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  buff_helper:
    path: ../pkg_pabuff_helper  
    # git:
    #   url: https://github.com/pabu500/pkg_pabuff_helper.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/project/gi_de/
    - assets/images/project/pa_ems/
    - assets/images/project/zsp/
    - assets/images/project/mbfc/
    - assets/images/project/sunseap/
    - assets/images/project/cw_p2/